### ISSUE TITLE
Issue running Edge browser on Mac OSX

### ISSUE THREAD

**Issue by alexander-dominguez** [crossbrowsertesting/selenium-webdriverio#9]
Passing the following object to my `capabilities` array works fine: 

```
{
  maxInstances: 5,
  platform: 'Win10',
  browserName: 'MicrosoftEdge'
}
```
However, I want to run Edge on Mac OSX also. The following object...

```
{
  maxInstances: 5,
  platform: 'MacOSX',
  browserName: 'MicrosoftEdge'
}
```
... causes this error: `ERROR webdriver: Request failed with status 500 due to Error: Could not find a match for the capabilities provided.`

Per the README, `MacOSX` should use the latest version by default, but it seems to be running a prior version --one that does not support MS Edge browser. Is there any way to achieve this, or will support be added in the near future?

**Comment by lkende** [comment]
@alexander-dominguez 

Hello. At the moment, MS Edge on Mac is unavailable for Selenium Tests. However, it is available for Live Tests.  We have an open task for enabling Mac/Edge that is in progress, so should be ready within the next couple of weeks (assuming no issues).

**Comment by alexander-dominguez** [comment]
Thanks for the prompt reply @lkende.
